279 add new method getroibyid on roimapmanager
image-js/image-js-typescript pull request #308
Opened 2023-04-18 20:59 UTC by EscapedGibbon

2023-04-19 07:34 UTC, targos commented
In general, please take the time to write a pull request description in English (do not use the default one based on the branch name)

2023-05-05 12:17 UTC, lpatiny requested changes

2023-05-05 12:17 UTC, lpatiny commented on src/roi/RoiMapManager.ts
> +    const thatRoi = rois.find((roi) => roi.id === roiID);
Could be renamed to `foundRoi`

2023-05-05 12:17 UTC, lpatiny commented on src/roi/RoiMapManager.ts
> +    } else {
The else is not necessary

2023-05-05 12:17 UTC, lpatiny commented on src/roi/RoiMapManager.ts
> +    if (thatRoi === undefined) {
In this case I would write
```
if(! thatRoi) {

}
```

2023-05-05 18:27 UTC, closed without merging