239 implement median filter for noise removal
image-js/image-js-typescript pull request #337
Opened 2023-05-12 07:33 UTC by EscapedGibbon

2023-06-14 08:27 UTC, lpatiny requested changes

2023-06-14 08:27 UTC, lpatiny commented on src/filters/medianFilter.ts
> +        for (let cellSizeRow = -kSize; cellSizeRow <= kSize; cellSizeRow++) {
cellRow and cellColumn would be better names I think

2023-06-14 08:27 UTC, lpatiny commented on src/filters/medianFilter.ts
> +    throw new Error('cellSize must be an odd number');
@targos If this also a RangeError ?

2023-06-14 08:27 UTC, lpatiny commented on src/filters/medianFilter.ts
> +  let kernel;
Just define it always as new Uint16Array(size). It may always be problematic that the variable may be 2 different kinds.

2023-06-14 08:27 UTC, lpatiny commented on src/filters/medianFilter.ts
> +  let kernel;
`kernel` seems a strange name. Maybe `cellValues`

2023-06-14 08:27 UTC, lpatiny commented on src/Image.ts
> +   * @param options.radius - Size of the area to calculate median value from.
You should only keep options, all the other parameters are defined in MedianFilterOptions

2023-06-14 08:27 UTC, lpatiny commented on src/filters/medianFilter.ts
> +  cellSize: number;
If we call it `cellSize` (like in pixelate) it should be be a radius but the actual size.

2023-06-14 08:44 UTC, targos commented on src/filters/medianFilter.ts
> +    throw new Error('cellSize must be an odd number');
yes

2023-06-14 10:45 UTC, EscapedGibbon commented
Conversations resolved

2023-06-14 11:43 UTC, stropitek commented on src/filters/medianFilter.ts
> +  // validateChannels(options.channels as number[], image);
?

2023-06-14 11:43 UTC, stropitek commented on src/filters/medianFilter.ts
> +   * The radius of the cell to extract xMedian from. Must be odd.
"xMedian" is confusing (I suppose it's related to implementation and should not be in the documentation)

2023-06-14 11:43 UTC, stropitek commented on src/filters/medianFilter.ts
> + * Apply a median filter to the image.
Please don't paraphrase the function's name. It should describe what the function does in 2-3 sentences, not state what the function is.

2023-06-14 11:43 UTC, stropitek commented on src/filters/medianFilter.ts
> +  borderValue: number;
In other methods of image-js having the `borderType` option, is this option also a required field?

2023-06-14 12:11 UTC, EscapedGibbon commented
Done

2023-06-16 11:15 UTC, stropitek commented on src/filters/medianFilter.ts
> + * Calculate a new image that replaces all pixel values by the median value inside the square area set in the options
```suggestion
 * Calculate a new image that replaces all pixel values by the median of neighbouring pixels.
```

2023-06-16 11:25 UTC, merged