refactor: rename bitDepth to depth
image-js/image-js-typescript pull request #445
Opened 2024-04-10 13:51 UTC by moonayyur

closes #444

2024-04-10 13:53 UTC, stropitek commented
Would it be simpler to remap `bitDepth` to `depth` when passing the options to fast-png?

2024-04-10 13:54 UTC, targos requested changes
I'm sorry but I don't see a good reason for making this big change.

2024-04-10 13:54 UTC, stropitek commented
> Would it be simpler to remap `bitDepth` to `depth` when passing the options to fast-png?

Simpler but mainly non-breaking

2024-04-10 14:53 UTC, targos commented on src/save/encodePng.ts
> +    },
Can you avoid the repetition with a variable?

2024-04-11 07:19 UTC, stropitek commented
You can merge with main to get rid of the CI errors

2024-04-11 07:21 UTC, targos commented
Can you please add a test that would fail before the fix?

2024-04-11 10:08 UTC, targos requested changes
You fix the `encodePng` function, so the test should execute that function, not the one from `fast-png` directly.

2024-04-11 10:19 UTC, moonayyur commented
> You fix the `encodePng` function, so the test should execute that function, not the one from `fast-png` directly.

So the image must be converted to 8 bits first ? Since the `encodePng` function only accepts a prop of type `Image` where `bitDepth` is mandatory (so we can't test directly with the default value of `fast-png`)

2024-04-11 11:07 UTC, targos commented
I don't see why it would have to be converted to 8 bits first. `bitDepth` is mandatory, but its value doesn't have to be 8.

2024-04-11 11:17 UTC, moonayyur commented
Oh, okay I had misunderstood this 
> Can you please add a test that would fail before the fix?

I thought I should write a test that shows the previous error

2024-04-11 11:24 UTC, targos commented
You should write a test that pass with the fix and doesn't pass without the fix.

2024-04-11 11:38 UTC, moonayyur commented
The previous error was that the attribute `depth` in `fast-png` wasn't getting any value from `img` since it was named `bitDepth`
But now `bitDepth` is renamed to `depth` inside `encodePng`, so I don't see how I could go back to the error in the test

2024-04-11 11:41 UTC, targos commented
You're correct, and that's not what I'm asking.
Somehow I'm not making myself clear but I don't know how to say it differently 😕

2024-04-12 17:24 UTC, targos approved these changes

2024-04-12 17:24 UTC, merged